### ISSUE TITLE
Не получается установить.

### ISSUE THREAD

**Issue by ctrlzzzzz** [zentavr/linet.mikrotik#1]
Добрый день. 
Сделал все по инструкции, добавил шаблоны, добавил хост, присоединил  шаблоны к хосту, поправил макросы, импортировал шаблоны преобразовании значений, установил Python 2.7.13  в env, поправил путь в **userparameter_mikrotik_getdata.conf**. В итоге в мониторинге в последних данных тишина. Если делать из консоли 
`/etc/zabbix/env/pyenv/bin/python /etc/zabbix/mikrotik/zabbix.py -H 192.168.1.1 -u apiuser -p passsssss`
Вывод получается такой: 
```
Loading .bgp from /etc/zabbix/mikrotik/plugins
Loading .irq from /etc/zabbix/mikrotik/plugins
Loading .radius from /etc/zabbix/mikrotik/plugins
Traceback (most recent call last):
  File "/etc/zabbix/mikrotik/zabbix.py", line 62, in <module>
    main()
  File "/etc/zabbix/mikrotik/zabbix.py", line 55, in main
    m.run(api, args.use_timestamps)
  File "/etc/zabbix/mikrotik/plugins/bgp.py", line 30, in run
    key='mikrotik.bgp.node[' + bgpitem['name'] + ',remote-as]',
TypeError: cannot concatenate 'str' and 'int' objects

```
Если делать так:
`/etc/zabbix/env/pyenv/bin/python /etc/zabbix/mikrotik/zabbix.py -H 192.168.1.1 -u apiuser -p passsssss -s -t`
То:
```
Traceback (most recent call last):
  File "/etc/zabbix/mikrotik/zabbix.py", line 62, in <module>
    main()
  File "/etc/zabbix/mikrotik/zabbix.py", line 46, in main
    **connect_args
  File "/etc/zabbix/env/pyenv/lib/python2.7/site-packages/librouteros/__init__.py", line 41, in connect
    transport = create_transport(host, **arguments)
  File "/etc/zabbix/env/pyenv/lib/python2.7/site-packages/librouteros/__init__.py", line 69, in create_transport
    raise ConnectionError(error)
librouteros.exceptions.ConnectionError: [Errno 111] Connection refused

```

Подскажите пожалуйста, что я делаю не так?

**Comment by zentavr** [comment]
Параметр “-s” включает поддержку SSL для API соединения (api-ssl в IP/Services Микротика, сертификат должен быть установлен).

Кстати, а Радиус у вас используется вообще?

**Comment by zentavr** [comment]
Ну и второе - какой комментарий на bgp peer стоит?

**Comment by ctrlzzzzz** [comment]
C "-s" все теперь понятно, комментария на bgp peer нету.

**Comment by zentavr** [comment]
Скорее всего это проблема, так как скрипт в противном случае будет использовать ID.

Я сейчас изменю код, но в item’прах будут светится циферки и будет не совсем тогда ясно от какого пира данные.

P.S.: кстати заббикс не любит кириллические комменты

**Comment by ctrlzzzzz** [comment]
Радиуса нету пока.

**Comment by ctrlzzzzz** [comment]
Сейчас комменты добавлю протестирую.

**Comment by zentavr** [comment]
@ctrlzzzzz - можно статус комманды выслать?

```
[zentavr@mtik-gw02] > /routing bgp peer print status
Flags: X - disabled, E - established
 0 E ;;; Ucomline
     name="ucomline" instance=default remote-address=192.168.0.1 remote-as=65535 tcp-md5-key="" nexthop-choice=default multihop=no route-reflect=no hold-time=15s ttl=default in-filter=UCOMLINE-IN out-filter=UCOMLINE-OUT
     address-families=ip update-source=192.168.0.254 default-originate=never remove-private-as=no as-override=no passive=no use-bfd=no remote-id=10.0.0.1 local-address=192.168.0.254 uptime=1d6m prefix-count=703282
     updates-sent=541969 updates-received=1426308 withdrawn-sent=839662 withdrawn-received=143111 remote-hold-time=3m used-hold-time=15s used-keepalive-time=5s refresh-capability=yes as4-capability=yes state=established

 1 E ;;; MasterNet
     name="masternet" instance=default remote-address=192.168.0.2 remote-as=65534 tcp-md5-key="" nexthop-choice=default multihop=no route-reflect=no hold-time=3m ttl=default in-filter=MASTERNET-IN out-filter=MASTERNET-OUT
     address-families=ip update-source=192.168.0.254 default-originate=always remove-private-as=no as-override=no passive=no use-bfd=no remote-id=172.16.0.1 local-address=192.168.0.254 uptime=1d6m22s prefix-count=699105
     updates-sent=1313732 updates-received=1225790 withdrawn-sent=233352 withdrawn-received=405439 remote-hold-time=1m30s used-hold-time=1m30s used-keepalive-time=30s refresh-capability=yes as4-capability=yes state=established
```
Какой-то странный у вас видимо `name` используется (число??)

**Comment by ctrlzzzzz** [comment]
Да, число.

**Comment by zentavr** [comment]
@ctrlzzzzz - попробуйте скачать [GH-1-Weird-BGP-Name](zentavr/linet.mikrotik/tree/GH-1-Weird-BGP-Name) бранч. Я положил #2 pull request.

**Comment by ctrlzzzzz** [comment]
Вот: 
 ```
/routing bgp peer print status
Flags: X - disabled, E - established
0 E name="44020" instance=default remote-address=xx.xx.xx.xx remote-as=44020
     tcp-md5-key="" nexthop-choice=default multihop=no route-reflect=no
     hold-time=3m ttl=255 in-filter=AS44020-bgp-in out-filter=AS44020-bgp-out
     address-families=ip default-originate=never remove-private-as=no
     as-override=no passive=no use-bfd=no remote-id=xx.xx.xx.xx
     local-address=xx.xx.xx.xx uptime=4d19h11m7s prefix-count=1 updates-sent=3
     updates-received=2 withdrawn-sent=0 withdrawn-received=0
     remote-hold-time=1m30s used-hold-time=1m30s used-keepalive-time=30s
     refresh-capability=yes as4-capability=yes state=established

1 E name="8595" instance=default remote-address=xx.xx.xx.xx remote-as=8595
     tcp-md5-key="" nexthop-choice=default multihop=no route-reflect=no
     hold-time=3m ttl=255 in-filter=AS8595-bgp-in out-filter=AS8595-bgp-out
     address-families=ip default-originate=never remove-private-as=no
     as-override=no passive=no use-bfd=no remote-id=xx.xx.xx.xx
     local-address=xx.xx.xx.xx uptime=2d18h52m29s prefix-count=1
     updates-sent=3 updates-received=1 withdrawn-sent=0 withdrawn-received=0
     remote-hold-time=1m30s used-hold-time=1m30s used-keepalive-time=30s
     refresh-capability=yes as4-capability=yes state=established

2 E ;;; up1
     name="39374" instance=default remote-address=xx.xx.xx.xx remote-as=39374
     tcp-md5-key="" nexthop-choice=default multihop=no route-reflect=no
     hold-time=3m ttl=255 in-filter=AS39374-bgp-in out-filter=AS39374-bgp-out
     address-families=ip default-originate=always remove-private-as=no
     as-override=no passive=no use-bfd=no remote-id=xx.xx.xx.xx
     local-address=xx.xx.xx.xx uptime=22h5m29s prefix-count=73 updates-sent=2
     updates-received=82 withdrawn-sent=0 withdrawn-received=9
     remote-hold-time=1m30s used-hold-time=1m30s used-keepalive-time=30s
     refresh-capability=yes as4-capability=yes state=established
```

**Comment by ctrlzzzzz** [comment]
тут 404:
https://github.com/zentavr/linet.mikrotik/issues/zentavr/linet.mikrotik/tree/GH-1-Weird-BGP-Name

**Comment by zentavr** [comment]
Вам нужен бранч GH-1-Weird-BGP-Name - вариант решения там.

**Comment by ctrlzzzzz** [comment]
Спасибо!!!
