### ISSUE TITLE
Script error when BGP peer is down

### ISSUE THREAD

**Issue by dcdamien** [zentavr/linet.mikrotik#4]
**Router OS Version**: 6.27

##### SUMMARY
Script fails when BGP peer is down and there is no prefix-count key received from RouterOS.

##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

* OS: `Ubuntu 16.04`
* Python: ` 2.7.12`
* Virtualenv: yes
* pip freeze:
```
chainmap==1.0.2
librouteros==2.1.0
```

##### STEPS TO REPRODUCE

```
/etc/zabbix/.venv/bin/python /etc/zabbix/mikrotik/zabbix.py -H 10.0.21.201 -u zabbix -p password -t
```

##### EXPECTED RESULTS

Script should handle correctly case when any of peers is down and prefix-count key is not found.

##### ACTUAL RESULTS

Script fails as below:

```
- mikrotik.bgp.node[cumru-fullbogons-bgp1,remote-as] "65332"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,prefix-count] "3135"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,disabled] "False"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,uptime] "1021996"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,state] "6"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,comment] ""
- mikrotik.bgp.node[cumru-fullbogons-bgp1,updates-received] "3266"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,updates-sent] "0"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,withdrawn-received] "131"
- mikrotik.bgp.node[cumru-fullbogons-bgp1,withdrawn-sent] "0"
- mikrotik.bgp.node[cumru-fullbogons-bgp2,remote-as] "65332"
Traceback (most recent call last):
  File "/etc/zabbix/mikrotik/zabbix.py", line 62, in <module>
    main()
  File "/etc/zabbix/mikrotik/zabbix.py", line 55, in main
    m.run(api, args.use_timestamps)
  File "/etc/zabbix/mikrotik/plugins/bgp.py", line 44, in run
    value=zabbix_escape(bgpitem['prefix-count'])
KeyError: 'prefix-count'
```

**Comment by zentavr** [comment]
Hi @dcdamien, thank you for reporting this.
I will look on this today.

**Comment by zentavr** [comment]
Please check GH-issue-4_BGP_missed_key branch

**Comment by zentavr** [comment]
@dcdamien - I pushed the code into master. Please check and reopen the issue if the problem still exists.

**Comment by dcdamien** [comment]
@zentavr this is fine now but new bug was introduced - #7
